### ISSUE TITLE
using midi instead of GPIO

### ISSUE THREAD

**Issue by farvardin** [nullpainter/drone#1]
hello,

this patch sounds great!

however, I didn't manage to make some sound with it, probably because of the GPIO requirement. I've tried to alter some values in the gpioRouter patch, for example vol, vco etc. using a slider, but I don't know the expected range of all those values. Could you help me?

**Comment by nullpainter** [comment]
Thank you! I did have sliders while debugging, which would have helped you. All GPIO input values are from 0-1. Good luck!

**Comment by farvardin** [comment]
@nullpainter thanks a lot, it worked!

I've made a patch only version, and I'm working on adding my akai midimix to control it as well:

![image](https://user-images.githubusercontent.com/477243/192118273-a641aed5-70e5-48d8-9441-004f45f8b1aa.png)

I wasn't sure about the wave, there is sine, triangle and both, I don't know if I've implemented it well, it will just send 0 or 1 to osc1_sin for example...

 

I've put my fork there: https://github.com/farvardin/nullpainter_drone

**Comment by nullpainter** [comment]
Oh wow, that is fantastic! I'll check it out in a bit.

Do the base waveforms not sound correct? They're driven by switches so will also be 1 or 0. This way I can enable or disable the wavetables by multiplying by the switch value.

I see you noticed the overdrive. That was a happy accident. I had already constructed the front panel when I was tidying the patch and something terrible was happening due to a miswire - however, it resulted in very cool audio. I had ideas about maybe hooking it up to OSC but didn't get around to it. I also didn't get around to working out whether the result was unique enough to keep. I'd be interested in your thoughts.

**Comment by nullpainter** [comment]
Just having a quick play. I guess you already know the octave selector isn't working, but I'm also not sure that the third and fourth oscillators are working correctly. They don't seem to be having that much of an effect on the sound.

**Comment by nullpainter** [comment]
You may also need to have a few more triggers - haven't spent long, but some toggles only seem to kick in when tweaking a slider. I realise that this may well be my bug. Because my sliders are fed from an analogue input, their values will always be slightly changing so there's a high chance that the triggers are missing in my original patch.

**Comment by farvardin** [comment]
@nullpainter I suppose the selectors and oscillators are correct, but only you can compare with the hardware version. As you suppose, the octave selector was only refreshed after the frequency was modified (because of the way puredata is handling "hot" and "cold" inlets). I've added a bang when changing the octave, which seems to trigger the oscillators, I can't figure if it does the job correctly, but I suppose it does, at least it's changing the sound.

![image](https://user-images.githubusercontent.com/477243/192143275-53797454-21f1-496c-b2cd-f5206ae22d96.png)

About the overdrive, I think it's a neat idea. It remind me a bit of the "brute factor" we can find on some arturia synth, it just add some dirtyness to the sound and it's great.

I've noticed a "noise" factor, along with the sine and triangle, but it doesn't look connected to the rest of the patch, so I suppose it's not used (yet?)

I suppose it could be possible to add a mix button for selecting the amount of sine and triangle, but it's not essential.

I've finished to adapt the patch to my MidiMix controller, and now it's working fine. I've also made a PDF with the values, so people can print it to cover their controller, it's what I've did with the LIRA-8 puredata synth (a clone of the lyra-8), which I recommend if you enjoy drones...

if you wish you can re-integrate the panel code into your repository, it could help more people to play with this great drone machine...

**Comment by farvardin** [comment]
what I might try to add is a way to store the drone parameters inside a text file, puredata can handle this, it's what was made with the LIRA-8 patch, it's convenient for keeping good sounding values...

**Comment by nullpainter** [comment]
I added noise before the physical design but didn't think it added enough interest to warrant adding to the synth. The philosophy of the synth was driven by including only what was strictly necessary, and the minimum amount in order to create a varied and interesting sound. This was also practical - there are only so many GPIO pins to play with, even with port expanders. This is why one oscillator is sacrificed for VCO, and why the first "octave" is significantly larger than a single octave (so I can have beating between very low frequencies).

This has been a very organic process and is my first synth, so I would love to hear of any improvements you may have.

I'd be very happy to re-integrate the panel code into my repository. I will also have a good test of your branch and fix up anything which doesn't match the hardware build. I suspect that this will largely be adding judicious trigger bangs where required. 

I'll check out the LIRA-8!

**Comment by nullpainter** [comment]
Sorry, only just having a chance to look at this now. I think the default octave state needs to be triggered on load - taking the state from git and disabling everything apart from the first and second oscillators, the second oscillator has no real impact until the octave selector is clicked.

I'll add that and see what else is required :-)

(edit: just changing the GUI elements to be init may do the trick...)

![image](https://user-images.githubusercontent.com/1732347/192702356-1ddd01cc-78d7-45cb-9815-f703cd98b133.png)

**Comment by nullpainter** [comment]
That has fixed a bunch of issues. The VCO is still not quite right though.

I can't create a fork of your fork in order to create the pull request. In the meantime, [here's](https://github.com/nullpainter/drone/commit/13ed44cbbd61f23fa2dcfc8f1edb6279961b0800) your `drone.pd` with the triggers on all GUI elements and with volume and frequency sliders changed to be logarithmic.

**Comment by nullpainter** [comment]
And the [VCO fix](https://github.com/nullpainter/drone/commit/e0dde3bc5ff6a9d86a6d60c9b7ee89dae762abf9)!

![image](https://user-images.githubusercontent.com/1732347/192711213-22ccddd7-dae2-42ba-bd4c-471a3b30077a.png)

![image](https://user-images.githubusercontent.com/1732347/192711265-03bb0769-dcff-4a7d-87de-84cb611ffe75.png)

**Comment by nullpainter** [comment]
Okay, clicking things randomly, I _think_ that may be all. I think the rule of thumb is - if twiddling a knob or clicking a button doesn't do anything, add a trigger 🤣

(I'm sure there's a less organic approach to this, but it's worked for me thus far...)

**Comment by farvardin** [comment]
@nullpainter I didn't know we could add a trigger like this, that's a clever trick. I've updated my repository, but I don't think I'll need to create a pull request (I've made some modifications in the readme for example), if you wish you might be able to integrate the code into your own repository...

Thank you for the fix! The VCO sounds indead much better!

**Comment by nullpainter** [comment]
Sure, I'd be happy to. Everything working from your perspective? Things doing what they sound like they ought to?

**Comment by farvardin** [comment]
@nullpainter Yes, I suppose everything is correct, for my tastes at least! I've tried to copy the settings from your youtube video and I get the impression it's not very similar, but I can't really tell because moving slightly a knob can change the sound greatly...

I've added for fun some noise, it could be improved, but at the moment it helps to give a different texture to the sounds:

![image](https://user-images.githubusercontent.com/477243/193479589-51e2a2fe-7029-46fe-8a74-b797b8619f0b.png)

**Comment by nullpainter** [comment]
Sorry for the unreasonable delay. Instead of merging in your code, I've decided to leave it as a separate fork. To this end, I have added a link to it in my README. Thanks again!

**Comment by farvardin** [comment]
great, thank you!
